var GHPATH = '/SMC-LUCKY-HOUSE';
var APP_PREFIX = 'gppwa_';
let VERSIONNAME = "1.0.4-02102025-beta";
var VERSION = VERSIONNAME;

var URLS = [
  `${GHPATH}/`,
  `${GHPATH}/index_data`,
  `${GHPATH}/index.html`,
  `${GHPATH}/manifest.webmanifest`,

  `${GHPATH}/Index_data/audio`,
  `${GHPATH}/Index_data/audio/Gacha aud press.mp3`,
  `${GHPATH}/Index_data/audio/Gacha aud pressed.mp3`,
  `${GHPATH}/Index_data/audio/Gacha aud pressed_long.mp3`,
  `${GHPATH}/Index_data/audio/Gacha aud start.mp3`,
  `${GHPATH}/Index_data/audio/press_btn.wav`,

  `${GHPATH}/Index_data/scripts`,
  `${GHPATH}/Index_data/scripts/continue.js`,
  `${GHPATH}/Index_data/scripts/tabs.js`,
  `${GHPATH}/Index_data/scripts/window_load.js`,

  `${GHPATH}/Index_data/scripts/mecha`,
  `${GHPATH}/Index_data/scripts/mecha/openx1.js`,

  `${GHPATH}/Index_data/scripts/pilot`,
  `${GHPATH}/Index_data/scripts/pilot/openx1.js`,

  `${GHPATH}/Index_data/styles`,
  `${GHPATH}/Index_data/scripts/classes.css`,
  `${GHPATH}/Index_data/scripts/root.css`,
  `${GHPATH}/Index_data/scripts/styles.css`,

  `${GHPATH}/Index_data/textures`,

  `${GHPATH}/Index_data/textures/cards`,

  `${GHPATH}/Index_data/textures/cards/mecha`,

  `${GHPATH}/Index_data/textures/cards/mecha/default`,
  `${GHPATH}/Index_data/textures/cards/mecha/default/Akashic.png`,
  `${GHPATH}/Index_data/textures/cards/mecha/default/Alborada.png`,
  `${GHPATH}/Index_data/textures/cards/mecha/default/Andromeda.png`,
  `${GHPATH}/Index_data/textures/cards/mecha/default/Arthur.png`,
  `${GHPATH}/Index_data/textures/cards/mecha/default/Aurora.png`,
  `${GHPATH}/Index_data/textures/cards/mecha/default/Boltus.png`,
  `${GHPATH}/Index_data/textures/cards/mecha/default/Caramel.png`,
  `${GHPATH}/Index_data/textures/cards/mecha/default/Death Knel.png`,
  `${GHPATH}/Index_data/textures/cards/mecha/default/Doomlight.png`,
  `${GHPATH}/Index_data/textures/cards/mecha/default/Dreadwolf.png`,
  `${GHPATH}/Index_data/textures/cards/mecha/default/Firefox.png`,
  `${GHPATH}/Index_data/textures/cards/mecha/default/Firestar.png`,
  `${GHPATH}/Index_data/textures/cards/mecha/default/Flamenco.png`,
  `${GHPATH}/Index_data/textures/cards/mecha/default/Gabriel.png`,
  `${GHPATH}/Index_data/textures/cards/mecha/default/Gaia.png`,
  `${GHPATH}/Index_data/textures/cards/mecha/default/Guerilla Hunter.png`,
  `${GHPATH}/Index_data/textures/cards/mecha/default/Hotsteel.png`,
  `${GHPATH}/Index_data/textures/cards/mecha/default/Hurricane.png`,
  `${GHPATH}/Index_data/textures/cards/mecha/default/Jojo.png`,
  `${GHPATH}/Index_data/textures/cards/mecha/default/Lancelot.png`,
  `${GHPATH}/Index_data/textures/cards/mecha/default/Michael.png`,
  `${GHPATH}/Index_data/textures/cards/mecha/default/Moon Rabbit.png`,
  `${GHPATH}/Index_data/textures/cards/mecha/default/Nebula.png`,
  `${GHPATH}/Index_data/textures/cards/mecha/default/Neutron Star.png`,
  `${GHPATH}/Index_data/textures/cards/mecha/default/Northern Knight.png`,
  `${GHPATH}/Index_data/textures/cards/mecha/default/Pulsar.png`,
  `${GHPATH}/Index_data/textures/cards/mecha/default/Ranger.png`,
  `${GHPATH}/Index_data/textures/cards/mecha/default/Raven.png`,
  `${GHPATH}/Index_data/textures/cards/mecha/default/Shiranui.png`,
  `${GHPATH}/Index_data/textures/cards/mecha/default/Skyfall.png`,
  `${GHPATH}/Index_data/textures/cards/mecha/default/Skyfire.png`,
  `${GHPATH}/Index_data/textures/cards/mecha/default/Skylark.png`,
  `${GHPATH}/Index_data/textures/cards/mecha/default/Snow Mirage.png`,
  `${GHPATH}/Index_data/textures/cards/mecha/default/Tempest.png`,
  `${GHPATH}/Index_data/textures/cards/mecha/default/Trio of Enders.png`,
  `${GHPATH}/Index_data/textures/cards/mecha/default/Twilight.png`,
  `${GHPATH}/Index_data/textures/cards/mecha/default/Ventorus.png`,

  `${GHPATH}/Index_data/textures/cards/pilot`,

  `${GHPATH}/Index_data/textures/cards/pilot/default`,
  `${GHPATH}/Index_data/textures/cards/pilot/default/Aya.png`,
  `${GHPATH}/Index_data/textures/cards/pilot/default/Belladonna.png`,
  `${GHPATH}/Index_data/textures/cards/pilot/default/Cyrus.png`,
  `${GHPATH}/Index_data/textures/cards/pilot/default/Fran.png`,
  `${GHPATH}/Index_data/textures/cards/pilot/default/Furanku.png`,
  `${GHPATH}/Index_data/textures/cards/pilot/default/Iori.png`,
  `${GHPATH}/Index_data/textures/cards/pilot/default/Ivan.png`,
  `${GHPATH}/Index_data/textures/cards/pilot/default/Jaka.png`,
  `${GHPATH}/Index_data/textures/cards/pilot/default/Jiu Chong.png`,
  `${GHPATH}/Index_data/textures/cards/pilot/default/Joanna.png`,
  `${GHPATH}/Index_data/textures/cards/pilot/default/Kije.png`,
  `${GHPATH}/Index_data/textures/cards/pilot/default/Kikina.png`,
  `${GHPATH}/Index_data/textures/cards/pilot/default/Kizuna Ai.png`,
  `${GHPATH}/Index_data/textures/cards/pilot/default/Lillian.png`,
  `${GHPATH}/Index_data/textures/cards/pilot/default/Lysa.png`,
  `${GHPATH}/Index_data/textures/cards/pilot/default/Matilda.png`,
  `${GHPATH}/Index_data/textures/cards/pilot/default/Mia.png`,
  `${GHPATH}/Index_data/textures/cards/pilot/default/Mila.png`,
  `${GHPATH}/Index_data/textures/cards/pilot/default/Mobius.png`,
  `${GHPATH}/Index_data/textures/cards/pilot/default/Nighthalk.png`,
  `${GHPATH}/Index_data/textures/cards/pilot/default/Ning.png`,
  `${GHPATH}/Index_data/textures/cards/pilot/default/Norma.png`,
  `${GHPATH}/Index_data/textures/cards/pilot/default/Opal.png`,
  `${GHPATH}/Index_data/textures/cards/pilot/default/Purity.png`,
  `${GHPATH}/Index_data/textures/cards/pilot/default/RED.png`,
  `${GHPATH}/Index_data/textures/cards/pilot/default/Riko.png`,
  `${GHPATH}/Index_data/textures/cards/pilot/default/Rom.png`,
  `${GHPATH}/Index_data/textures/cards/pilot/default/Serena.png`,
  `${GHPATH}/Index_data/textures/cards/pilot/default/Shin.png`,
  `${GHPATH}/Index_data/textures/cards/pilot/default/Silver Deacon.png`,
  `${GHPATH}/Index_data/textures/cards/pilot/default/Tarantula.png`,
  `${GHPATH}/Index_data/textures/cards/pilot/default/Vanessa.png`,
  `${GHPATH}/Index_data/textures/cards/pilot/default/Villar.png`,
  `${GHPATH}/Index_data/textures/cards/pilot/default/Vita.png`,
  `${GHPATH}/Index_data/textures/cards/pilot/default/Yang.png`,
  `${GHPATH}/Index_data/textures/cards/pilot/default/Yulia.png`,
  `${GHPATH}/Index_data/textures/cards/pilot/default/Yutong.png`,
  `${GHPATH}/Index_data/textures/cards/pilot/default/Zoe.png`,

  `${GHPATH}/Index_data/textures/images`,

  `${GHPATH}/Index_data/textures/images/mecha`,

  `${GHPATH}/Index_data/textures/images/mecha/default`,
  `${GHPATH}/Index_data/textures/images/mecha/default/Akashic.png`,
  `${GHPATH}/Index_data/textures/images/mecha/default/Alborada.png`,
  `${GHPATH}/Index_data/textures/images/mecha/default/Andromeda.png`,
  `${GHPATH}/Index_data/textures/images/mecha/default/Arthur.png`,
  `${GHPATH}/Index_data/textures/images/mecha/default/Aurora.png`,
  `${GHPATH}/Index_data/textures/images/mecha/default/Boltus.png`,
  `${GHPATH}/Index_data/textures/images/mecha/default/Caramel.png`,
  `${GHPATH}/Index_data/textures/images/mecha/default/Death Knel.png`,
  `${GHPATH}/Index_data/textures/images/mecha/default/Doomlight.png`,
  `${GHPATH}/Index_data/textures/images/mecha/default/Dreadwolf.png`,
  `${GHPATH}/Index_data/textures/images/mecha/default/Firefox.png`,
  `${GHPATH}/Index_data/textures/images/mecha/default/Firestar.png`,
  `${GHPATH}/Index_data/textures/images/mecha/default/Flamenco.png`,
  `${GHPATH}/Index_data/textures/images/mecha/default/Gabriel.png`,
  `${GHPATH}/Index_data/textures/images/mecha/default/Gaia.png`,
  `${GHPATH}/Index_data/textures/images/mecha/default/Guerilla Hunter.png`,
  `${GHPATH}/Index_data/textures/images/mecha/default/Hotsteel.png`,
  `${GHPATH}/Index_data/textures/images/mecha/default/Hurricane.png`,
  `${GHPATH}/Index_data/textures/images/mecha/default/Jojo.png`,
  `${GHPATH}/Index_data/textures/images/mecha/default/Lancelot.png`,
  `${GHPATH}/Index_data/textures/images/mecha/default/Michael.png`,
  `${GHPATH}/Index_data/textures/images/mecha/default/Moon Rabbit.png`,
  `${GHPATH}/Index_data/textures/images/mecha/default/Nebula.png`,
  `${GHPATH}/Index_data/textures/images/mecha/default/Neutron Star.png`,
  `${GHPATH}/Index_data/textures/images/mecha/default/Northern Knight.png`,
  `${GHPATH}/Index_data/textures/images/mecha/default/Pulsar.png`,
  `${GHPATH}/Index_data/textures/images/mecha/default/Ranger.png`,
  `${GHPATH}/Index_data/textures/images/mecha/default/Raven.png`,
  `${GHPATH}/Index_data/textures/images/mecha/default/Shiranui.png`,
  `${GHPATH}/Index_data/textures/images/mecha/default/Skyfall.png`,
  `${GHPATH}/Index_data/textures/images/mecha/default/Skyfire.png`,
  `${GHPATH}/Index_data/textures/images/mecha/default/Skylark.png`,
  `${GHPATH}/Index_data/textures/images/mecha/default/Snow Mirage.png`,
  `${GHPATH}/Index_data/textures/images/mecha/default/Tempest.png`,
  `${GHPATH}/Index_data/textures/images/mecha/default/Trio of Enders.png`,
  `${GHPATH}/Index_data/textures/images/mecha/default/Twilight.png`,
  `${GHPATH}/Index_data/textures/images/mecha/default/Ventorus.png`,

  `${GHPATH}/Index_data/textures/images/pilot`,

  `${GHPATH}/Index_data/textures/images/pilot/default`,
  `${GHPATH}/Index_data/textures/images/pilot/default/Aya.png`,
  `${GHPATH}/Index_data/textures/images/pilot/default/Belladonna.png`,
  `${GHPATH}/Index_data/textures/images/pilot/default/Cyrus.png`,
  `${GHPATH}/Index_data/textures/images/pilot/default/Fran.png`,
  `${GHPATH}/Index_data/textures/images/pilot/default/Furanku.png`,
  `${GHPATH}/Index_data/textures/images/pilot/default/Iori.png`,
  `${GHPATH}/Index_data/textures/images/pilot/default/Ivan.png`,
  `${GHPATH}/Index_data/textures/images/pilot/default/Jaka.png`,
  `${GHPATH}/Index_data/textures/images/pilot/default/Jiu Chong.png`,
  `${GHPATH}/Index_data/textures/images/pilot/default/Joanna.png`,
  `${GHPATH}/Index_data/textures/images/pilot/default/Kije.png`,
  `${GHPATH}/Index_data/textures/images/pilot/default/Kikina.png`,
  `${GHPATH}/Index_data/textures/images/pilot/default/Kizuna Ai.png`,
  `${GHPATH}/Index_data/textures/images/pilot/default/Lillian.png`,
  `${GHPATH}/Index_data/textures/images/pilot/default/Lysa.png`,
  `${GHPATH}/Index_data/textures/images/pilot/default/Matilda.png`,
  `${GHPATH}/Index_data/textures/images/pilot/default/Mia.png`,
  `${GHPATH}/Index_data/textures/images/pilot/default/Mila.png`,
  `${GHPATH}/Index_data/textures/images/pilot/default/Mobius.png`,
  `${GHPATH}/Index_data/textures/images/pilot/default/Nighthalk.png`,
  `${GHPATH}/Index_data/textures/images/pilot/default/Ning.png`,
  `${GHPATH}/Index_data/textures/images/pilot/default/Norma.png`,
  `${GHPATH}/Index_data/textures/images/pilot/default/Opal.png`,
  `${GHPATH}/Index_data/textures/images/pilot/default/Purity.png`,
  `${GHPATH}/Index_data/textures/images/pilot/default/RED.png`,
  `${GHPATH}/Index_data/textures/images/pilot/default/Riko.png`,
  `${GHPATH}/Index_data/textures/images/pilot/default/Rom.png`,
  `${GHPATH}/Index_data/textures/images/pilot/default/Serena.png`,
  `${GHPATH}/Index_data/textures/images/pilot/default/Shin.png`,
  `${GHPATH}/Index_data/textures/images/pilot/default/Silver Deacon.png`,
  `${GHPATH}/Index_data/textures/images/pilot/default/Tarantula.png`,
  `${GHPATH}/Index_data/textures/images/pilot/default/Vanessa.png`,
  `${GHPATH}/Index_data/textures/images/pilot/default/Villar.png`,
  `${GHPATH}/Index_data/textures/images/pilot/default/Vita.png`,
  `${GHPATH}/Index_data/textures/images/pilot/default/Yang.png`,
  `${GHPATH}/Index_data/textures/images/pilot/default/Yulia.png`,
  `${GHPATH}/Index_data/textures/images/pilot/default/Yutong.png`,
  `${GHPATH}/Index_data/textures/images/pilot/default/Zoe.png`,

  `${GHPATH}/Index_data/textures/gatcha`,
  `${GHPATH}/Index_data/textures/gatcha/1d.png`,
  `${GHPATH}/Index_data/textures/gatcha/2c.png`,
  `${GHPATH}/Index_data/textures/gatcha/3b.png`,
  `${GHPATH}/Index_data/textures/gatcha/4a.png`,
  `${GHPATH}/Index_data/textures/gatcha/5s.png`,
  `${GHPATH}/Index_data/textures/gatcha/6sp.png`,
  `${GHPATH}/Index_data/textures/gatcha/7ss.png`,

  `${GHPATH}/Index_data/textures/gui`,
  `${GHPATH}/Index_data/textures/gui/bg_inner.png`,
  `${GHPATH}/Index_data/textures/gui/bg_overlay.png`,
  `${GHPATH}/Index_data/textures/gui/company.png`,
  `${GHPATH}/Index_data/textures/gui/floor.png`,
  `${GHPATH}/Index_data/textures/gui/list_bg.png`,
  `${GHPATH}/Index_data/textures/gui/logo.png`,
  `${GHPATH}/Index_data/textures/gui/opx1.png`,
  `${GHPATH}/Index_data/textures/gui/opx10.png`,
  `${GHPATH}/Index_data/textures/gui/tab_horizontal.png`,
  `${GHPATH}/Index_data/textures/gui/tab_off.png`,
  `${GHPATH}/Index_data/textures/gui/tab_vertical.png`,
  `${GHPATH}/Index_data/textures/gui/tabs_continer.png`,
  `${GHPATH}/Index_data/textures/gui/cards_continer.png`,

  `${GHPATH}/Index_data/textures/system`,
  `${GHPATH}/Index_data/textures/system/icon.png`,

  `${GHPATH}/Index_data/textures/videos`,
  `${GHPATH}/Index_data/textures/videos/Gacha vid press.mp4`,
  `${GHPATH}/Index_data/textures/videos/Gacha vid pressed 1c.mp4`,
  `${GHPATH}/Index_data/textures/videos/Gacha vid pressed 2b.mp4`,
  `${GHPATH}/Index_data/textures/videos/Gacha vid pressed 3a.mp4`,
  `${GHPATH}/Index_data/textures/videos/Gacha vid pressed 4s.mp4`,
  `${GHPATH}/Index_data/textures/videos/Gacha vid pressed 5sp.mp4`,
  `${GHPATH}/Index_data/textures/videos/Gacha vid pressed 6ss.mp4`,
  `${GHPATH}/Index_data/textures/videos/Gacha vid pressed.mp4`,
  `${GHPATH}/Index_data/textures/videos/Gacha vid start.mp4`
];
self.addEventListener('install', event => {
  event.waitUntil(caches.open(VERSION).then(cache => cache.addAll(URLS)));
});
self.addEventListener('fetch', event => {
  event.respondWith(caches.match(event.request).then(response => {
    if (response) {
      return response;
    }
    return fetch(event.request);
    })
  );
});